# Generated by Django 4.1.7 on 2023-04-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_options_alter_product_options_and_more'),
    ]

    operations = [
        # migrations.RunSQL("""
        # # Uploading migration
        # ""","""
        # # downgrading migration if you don't mention django don't revert it.
        # """)
    ]
